Robustify incompletness marking
We now start assuming the backup is incomplete, and mark it as complete once
we're finished. This is the correct way to do it, the other way was just lazy.

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -61,8 +61,10 @@ echo "pid: ${BASHPID}" >> "${info_file}"
 # make sure the destination directory exists
 mkdir -p "${DEST}"
 
-# create a time-stamped directory for this backup
-backup_dir="${DEST}/backup-$(date '+%Y-%m-%dT%H:%M:%S')"
+# create time-stamped directories for this backup
+backup_timestamp="$(date '+%Y-%m-%dT%H:%M:%S')"
+incomplete_backup_dir="${DEST}/incomplete-backup-${backup_timestamp}"
+complete_backup_dir="${DEST}/backup-${backup_timestamp}"
 
 # this link points to the most recent backup. it's used as a simple way to get
 # the location of the most recent backup, as well as a way to chain the most
@@ -71,7 +73,7 @@ backup_dir="${DEST}/backup-$(date '+%Y-%m-%dT%H:%M:%S')"
 current_link="${DEST}/current"
 
 # start backing things up!
-echo "Backing up '${SOURCE}' to '${backup_dir}'..."
+echo "Backing up '${SOURCE}' to '${incomplete_backup_dir}'..."
 echo
 
 # use rsync and back everything up, telling it to be frugal with CPU and IO
@@ -102,7 +104,7 @@ nice -n19 ionice -c3 rsync \
   --exclude '/mnt/*' \
   --exclude "${DEST}" \
   \
-  "${SOURCE}" "${backup_dir}"
+  "${SOURCE}" "${incomplete_backup_dir}"
 
 rsync_exit_code="${?}"
 
@@ -114,19 +116,25 @@ rsync_exit_code="${?}"
 # orphaned.
 echo
 if [ "${rsync_exit_code}" -eq "0" ]; then
-  echo "Marking '${backup_dir}' as the current backup..."
-  rm -f "${current_link}" && ln -s "${backup_dir}" "${current_link}"
-else
-  echo "Backup exited before completing, marking backup as interrupted..."
+  echo "Marking backup as complete..."
+  mv "${incomplete_backup_dir}" "${complete_backup_dir}"
 
-  # mark the backup as incomplete by renaming its folder
-  interrupted_dir="$(dirname ${backup_dir})/interrupted-$(basename ${backup_dir})"
-  mv "${backup_dir}" "${interrupted_dir}"
+  echo "Marking '${complete_backup_dir}' as the current backup..."
+  rm -f "${current_link}" && ln -s "${complete_backup_dir}" "${current_link}"
+else
+  echo "Backup indicated failure (code ${rsync_exit_code})"
+  echo "Leaving backup marked as incomplete."
+
+  # bail out now, since the rest of the code depends on us having a good backup
+  echo
+  echo "Backup failed."
+
+  exit ${rsync_exit_code}
 fi
 
 # remove old backups
 echo
-echo "Removing old backups from '${DEST}'"
+echo "Removing old backups from '${DEST}':"
 
 present="$(date +%s)"
 for old_backup_dir in ${DEST}/backup-*; do
@@ -136,10 +144,10 @@ for old_backup_dir in ${DEST}/backup-*; do
   fi
 
   # pull the date (everything after the first '-') out of the directory name
-  dirname="$(basename ${old_backup_dir} | cut -d '-' -f 2-)"
+  timestamp="$(basename ${old_backup_dir} | cut -d '-' -f 2-)"
 
   # get the old date in UNIX time so we can calculate how many days old it is
-  past="$(date -d ${dirname} +%s)"
+  past="$(date -d ${timestamp} +%s)"
 
   # bail if we couldn't get a date
   if [[ "$?" -ne "0" ]]; then
@@ -151,7 +159,7 @@ for old_backup_dir in ${DEST}/backup-*; do
   # since it will only contain hardlinks, it's safe to remove backups as the
   # hard links will always just point to the physical file on disk.
   if [[ "$(( (present - past) / (60 * 60 * 24) ))" -gt ${DAYS_TO_KEEP} ]]; then
-    echo "  Removing '${old_backup_dir}'..."
+    echo "  Removing '${old_backup_dir}'"
     rm -rf "${old_backup_dir}"
   fi
 done
@@ -160,3 +168,6 @@ echo "Done removing old backups."
 
 echo
 echo "Backup complete!"
+
+# exit with success!
+exit 0
